cmd/iris/client.go
cmd/iris/node.go
cmd/iris/rest.go
glide.lock
glide.yaml

IRISHUB-33
基于iris-hub 0.1.0版本修复delegate超过1/3网络崩溃问题

IRISHUB-33 基于iris-hub 0.1.0版本修复delegate超过1/3网络崩溃问题

---

app/context.go
cmd/iriscli/offline_sign.go

The BroadcastTxAsync method should not be used and should be replaced with BroadcastTxSync. the reason:
The return result of BroadcastTxAsync has not passed the checkTx process of the app, and the illegal transaction cannot be found in time;
The result of BroadcastTxSync is passed through the app's checkTx process, which ensures that the transaction is executed correctly unless unexpected.

IRISHUB-9：The BroadcastTxAsync replaced with BroadcastTxSync

---

Gopkg.lock
tools/context.go
tools/prometheus/consensus/metrics.go
tools/prometheus/mempool/metrics.go
tools/prometheus/p2p/metrics.go
tools/prometheus/server.go

IRISHUB-34：irishub添加prometheus监控功能(添加p2p,memo监控，系统监控)

IRISHUB-34：irishub添加prometheus监控功能(添加p2p,memo监控，系统监控)

---

client/bank/lcd/rest.go
client/bank/lcd/sendtx.go
client/context/context.go
client/gov/cli/query.go
client/gov/common.go
client/gov/lcd/query.go
client/gov/lcd/sendtx.go
client/lcd/lcd.go
client/lcd/swaggerui/swagger.json
client/slashing/lcd/rest.go
client/slashing/lcd/sendtx.go
client/stake/cli/query.go
client/stake/cli/sendtx.go
client/stake/common.go
client/stake/lcd/query.go
client/stake/lcd/rest.go
client/stake/lcd/sendtx.go
client/stake/lcd/utils.go

Main changes:
* Improve API docs on swagger-ui page.
* Convert all token and share to its main unit in query. For instance, 1000000000000000000iris-atto equals to 1iris
* Convert token and share to mini unit in sendtx.  For instance, 1iris equals to 1000000000000000000iris-atto

IRISHUB-256: improve api docs and convert all token to its main unit

---

docs/modules/record/README.md
docs/modules/record/download.md
docs/modules/record/query.md
docs/modules/record/submit.md

Update English doc for record module for issue #571

R4R: Update English doc for record module

---

Gopkg.lock
Gopkg.toml
client/lcd/lcd.go
client/lcd/test_helpers.go
client/tendermint/rpc/validatorset.go
docker-compose.yml
modules/gov/handler.go
modules/slashing/keeper.go
modules/slashing/tick.go
modules/stake/keeper/slash.go
store/cachekvstore.go
store/cachekvstore_test.go
store/gaskvstore_test.go
store/iavlstore_test.go
store/list_test.go
store/memiterator.go
store/multistoreproof_test.go
store/prefixstore.go
store/prefixstore_test.go
store/queue_test.go
store/rootmultistore_test.go
store/tracekvstore_test.go
store/transientstore_test.go
types/stake.go
types/store.go

https://github.com/cosmos/cosmos-sdk/pull/2900
https://github.com/cosmos/cosmos-sdk/pull/2932

R4R: Add unit tests for store and merge PRs

---

app/sim_test.go
modules/auth/ante.go
modules/auth/ante_test.go
modules/auth/stdtx.go
modules/auth/stdtx_test.go
modules/bank/keeper.go
modules/bank/msgs_test.go
modules/bank/simulation/msgs.go
modules/slashing/handler_test.go
modules/slashing/keeper_test.go
modules/slashing/tick_test.go
modules/stake/types/msg_test.go
types/coin.go
types/coin_benchmark_test.go
types/coin_test.go
types/int.go
types/int_test.go
types/tx_msg.go

1. Add Safety Measures to Coin/Coins
https://github.com/cosmos/cosmos-sdk/pull/2797
2. Limit total number of signatures per transaction
https://github.com/cosmos/cosmos-sdk/pull/2800 
3. Transaction ValidateBasic
https://github.com/cosmos/cosmos-sdk/pull/2863

R4R: Merge PRs: 2797, 2800 and 2863

---

client/bank/cli/sign.go

```
cmd.MarkFlagRequired(client.FlagChainID)
```
The above code doesn't make sense. Because flag `client.FlagChainID` is not defined in this field.

R4R: Add chain-id value checking for sign command

---

app/v0/genesis.go

1. CollectStdTxs() must check DelegatorAddr
https://github.com/cosmos/cosmos-sdk/pull/3004

R4R: Make more validate about the `MsgCreateValidator` in CollectStdTxs

---

app/v0/export.go
client/stake/utils.go
modules/slashing/keeper_test.go
modules/stake/genesis.go
modules/stake/genesis_test.go
modules/stake/handler.go
modules/stake/keeper/delegation.go
modules/stake/keeper/delegation_test.go
modules/stake/keeper/keeper.go
modules/stake/keeper/key.go
modules/stake/keeper/key_test.go
modules/stake/keeper/slash_test.go
modules/stake/keeper/test_common.go
modules/stake/keeper/validator.go
modules/stake/keeper/validator_test.go
modules/stake/querier/queryable_test.go
modules/stake/stake.go
modules/stake/types/genesis.go
modules/stake/types/validator.go

refer to: https://github.com/cosmos/cosmos-sdk/pull/3055

R4R: use address instead of bond height / intratxcounter for deduplication

---

modules/gov/handler.go
modules/upgrade/tally.go
types/decimal_test.go

closes: https://github.com/irisnet/irishub/issues/979

R4R:  only use the bonded validator for upgrade tally and gov slash

---

types/protocol.go

`protocol` have its own codec but iriscli don't register these two structures.
I think it's better not to register these structures that don't need to be modified.

R4R: Don't register struct of protocol

---

client/context/broadcast.go

fix irislcd panic error:
```
E[9016-01-09|14:49:21.635] Panic in RPC HTTP handler                    module=irislcd err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 8 [running]:\nruntime/debug.Stack(0xc000831200, 0xdadb60, 0x1a9a320)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc00000cfe0, 0x133a400, 0xc0000700e0, 0xbf05843c65b2d8fa, 0xc6e0f3da, 0x1ab3620, 0xc00019a700)
/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:133 +0x50c\npanic(0xdadb60, 0x1a9a320)
/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/client/context.CLIContext.BroadcastTxSync( …
```

Add err checking for broadcast tx sync

---

app/baseapp.go
modules/auth/ante.go

Merge: https://github.com/cosmos/cosmos-sdk/pull/3244
This issue is not severe for us. Because we don't plan to enable block gas limit.

R4R: Fix infinite gas   meter utilization during aborted ante handler executions

---

docs/.vuepress/config.js
docs/cli-client/README.md
docs/zh/cli-client/README.md

* Distribution module missing from the sidebar
* Broken links for record and lcd in cli README

R4R: Fix cli sidebar and module command list

---

mock/app.go
modules/distribution/tests/allocation_test.go
modules/distribution/tests/delegation_test.go
modules/distribution/tests/keeper_test.go
modules/distribution/tests/test_common.go
modules/distribution/tests/validator_test.go

Earlier the tests were moved to tests/module simply to get rid of circular dependency.  By putting the tests under a subdirectory of the module we can achieve the same purpose, thus the moving back.

R4R: Move distribution tests back to its module but under a sub-folder

---

client/upgrade/cli/query.go

```
iriscli upgrade query-signals
No validators have started the new version.
iriscli upgrade query-signals                                                          
siganalsVotingPower/totalVotingPower = 0.5000000000
iriscli upgrade query-signals --detail                                                 
fva15cv33a67cfey5eze7238hck6yngw3694ak2elm   100.0000000000
siganalsVotingPower/totalVotingPower = 0.5000000000
```

R4R: Enhance the query-signals

---

app/baseapp.go
client/slashing/cli/query.go
client/slashing/lcd/query.go
client/tendermint/rpc/validatorset.go
docs/cli-client/stake/unjail.md
docs/cli-client/stake/validator.md
docs/cli-client/stake/validators.md
docs/cli-client/tendermint/validator-set.md
docs/features/stake.md
docs/get-started/Validator-Node.md
docs/zh/cli-client/stake/unjail.md
docs/zh/cli-client/stake/validator.md
docs/zh/cli-client/stake/validators.md
docs/zh/cli-client/tendermint/validator-set.md
docs/zh/features/stake.md
docs/zh/get-started/Validator-Node.md
types/context.go

- PR https://github.com/irisnet/irishub/pull/1281 change valiator pubkey prefix, so we have to change sign-info query handler.
- Fix unit test failures for empty CoinFlowTags

R4R: fix unit test failure and  change prefix for sign-info query

---

modules/gov/keeper.go
types/contexttags.go

The missed coin flow record only tracks the gov deposit address. It is a dead address. So rainbow app won't track this address.

R4R: Add coin flow record for gov deposit burn

---

CHANGELOG.md
Dockerfile

Although there is a warning now, it can be compiled successfully.

R4R: Fix build in alpine

---

modules/auth/ante.go

This is especially helpful in cases where the account balance is zero (empty). In that case, the error message is " is less than <coins>", which confusing.

Improve error message for insufficient balance

---

client/stake/lcd/query.go
client/stake/lcd/utils.go
lite/swagger-ui/swagger.yaml
modules/stake/handler_test.go
modules/stake/keeper/validator.go
modules/stake/keeper/validator_test.go
modules/stake/querier/queryable.go
modules/stake/querier/queryable_test.go
types/errors.go
types/queryable.go

Closes: https://github.com/irisnet/irishub/issues/1330

R4R: Add pagination params for lcd validators query

---

modules/slashing/keeper.go

R4R: Check the validator existence and validator status before getting its pubkey

---

app/v0/protocol_v0.go
client/bank/lcd/query.go
client/context/query.go
modules/auth/account_test.go
modules/auth/ante_test.go
modules/auth/keeper.go
modules/auth/querier.go
modules/auth/querier_test.go
modules/auth/test_utils.go

Ref: https://github.com/irisnet/irishub/issues/1374

R4R: Add querier for account query

---

client/utils/rest.go
client/utils/txcontext.go

Closes: https://github.com/irisnet/irishub/issues/1386

R4R: Add memo to LCD TxContext

---

modules/stake/keeper/delegation.go

Ref: https://github.com/irisnet/irishub/issues/1383
Reverts: https://github.com/irisnet/irishub/pull/1388
The `minTime` is part of `ResponseDeliverTx.Data`. PR #1388 will make the `last_results_hash` is inconsistent on different nodes. 
This is not an optional upgrade, so revert it.

R4R: Revert "Improve result tags for unbond and redelegate"

---

docs/light-client/README.md
docs/resources/delegator-faq.md
docs/resources/validator-faq.md
docs/zh/light-client/README.md
docs/zh/resources/delegator-faq.md
docs/zh/resources/validator-faq.md

https://github.com/irisnet/irishub/issues/1376

R4R: Fix the light-client and resources section of docs 

---

app/v1/asset/msgs.go

R4R: Reserve iris as keyword for asset symbol name

---

app/baseapp.go
app/protocol/engine.go
app/protocol/types.go
app/v0/protocol_v0.go
app/v1/protocol_v1.go

The prometheus registry register one metric twice will cause panic.

R4R: Reset the prometheus registry when loading a new protocol

---

app/v1/coinswap/internal/keeper/swap.go

Correct formula should be:
```
(1000 * x * ∆y) / (997 * (y - ∆y)) + 1
```
Which the spec describes in section 3.2.2: <https://github.com/runtimeverification/verified-smart-contracts/blob/uniswap/uniswap/x-y-k.pdf>

R4R: Fix GetInputAmount formula

---

app/v1/auth/ante.go
types/gas.go
types/gas_test.go

Resolves: https://github.com/irisnet/irishub/issues/1851
***test result:*** 
|  logarithm | total gas | ReadPerByte | WritePerByte | blockstore | other |
| ---------- | --------- | ------------- | ------------- | ---------- | ------ | 
| - |  6742 | 442 | 3070 | 2790 | 440 | 
| 1.1 | 3732 | 230 | 272 | 2790 | 440 | 
| 1.2 | 3491 | 119 | 142 | 2790 |  440 |

R4R: Decrease gas consumption by logarithm

---

app/v2/coinswap/alias.go
app/v2/coinswap/internal/keeper/swap_test.go
app/v2/coinswap/internal/types/msgs.go
app/v2/coinswap/internal/types/test_common.go
app/v2/coinswap/internal/types/utils.go
client/context/context.go
types/coin.go
types/coin_test.go
types/coin_type_test.go

R4R: Update denom's specification

---

app/v1/auth/keeper.go
app/v2/coinswap/internal/types/msgs.go
types/asset.go

Resolves: https://github.com/irisnet/irishub/issues/1960
After traversing all the keys of the `acc` store, I get the diff from two node with different app hashes.
```
totalSupply count: 3
totalSupply::280000000000000000002u-t505854-min
totalSupply:i.t505854:200000000000000000000t505854-min
totalSupply:i.t876757:200000000000000000000t876757-min
```
and
```
totalSupply count: 3
totalSupply::280000000000000000002u-t876757-min
totalSupply:i.t505854:200000000000000000000t505854-min
totalSupply:i.t876757:200000000000000000000t876757-min
```
We store an empty key path for all tokens with the prefix "u-", this is not need.

R4R: Do not init total supply for swap coins

---

CHANGELOG.md
docs/software/How-to-install-irishub.md
docs/zh/software/How-to-install-irishub.md
go.mod
go.sum
lite/swagger-ui/swagger.yaml
version/version.go

- Bump Tendermint version to irisnet/tendermint [v0.31.2](https://github.com/irisnet/tendermint/releases/tag/v0.31.2) to fix the p2p panic error.
- Update irishub version to v0.15.4

R4R: Bump Tendermint version to irisnet/tendermint v0.31.2

---

types/coin.go

Resolves: https://github.com/irisnet/irishub/issues/2054
`fmt.Errorf()` returns errors.errorString
```golang
type errorString struct {
s string
}
```
On panic, using string type has the same effect.

R4R: Panic with string type

---

app/v1/distribution/keeper/querier.go
app/v1/gov/queryable.go
app/v1/stake/querier/queryable.go
app/v3/gov/queryable.go
modules/distribution/keeper/querier.go
modules/gov/queryable.go
modules/stake/querier/queryable.go
tests/cli/bank_test.go

Incorrect input parameter in querier, such as
```go
if errRes != nil {
return nil, sdk.MarshalResultErr(err)
}
```

R4R: Fix querier error msg

---

app/v3/service/internal/keeper/upgrade.go

a new param is added in v3/service module, so reset the param set, other params are equal to the mainnet.

R4R: Reset params on upgrading

---

CHANGELOG.md
docs/get-started/install.md
docs/zh/get-started/install.md
go.mod
go.sum
lite/swagger-ui/swagger.yaml
version/version.go

Bump ledger-cosmos-go to support cosmos ledger 2.0
Fixed: #2380 
Closes: #2393

R4R: Bump ledger-cosmos-go version

---

docs/get-started/install.md
docs/zh/get-started/install.md

Fixes issue that comes from copy/paste the code block as-is since the variables defined in subsequent lines are not yet available when they are appended to `.bashrc`. This results in failure when `make get_tools install` is called due to attempts to install to `/bin` directly rather than `$HOME/go/bin` as we would expect since `$GOPATH` evaluates to an empty string when the `GOBIN` export is evaluated.
https://github.com/cosmos/cosmos-sdk/issues/2973#issuecomment-443404339

Update install.md ENV variable script 

---

CHANGELOG.md
go.mod
go.sum
scripts/protoc-swagger-gen.sh

Release v1.0.0

---

app/app.go
app/modules.go
go.mod
go.sum
simapp/app.go

ref: https://github.com/bianjieai/tibc-go/pull/122

fix: solve proposal handler route conflict 

---

docs/get-started/state-sync.md

replace IP with domain name, sentry-0.mainnet.irisnet.org and sentry-1.mainnet.irisnet.org

Update state-sync in docs
