irisnet/irishub

Dockerfile, Makefile, cmd/iris/rest_test.go
=> merge feature/pangu to master

docs/modules/fee-token/feeToken.md
=> fee token spec

tools/prometheus/governance/metrics.go, tools/prometheus/server_test.go
=> IRISHUB-222: add governanace monitoring terms

Gopkg.lock, Gopkg.toml, app/genesis.go
http://jira.bianjie.ai/browse/IRISHUB-364
=> IRISHUB-364: fix bug in genesis initialize

client/gov/cli/flags.go, client/gov/cli/query.go, cmd/iriscli/main.go, modules/gov/params/gov_params.go
```
cat param.json
{
"gov": {
"Gov/gov/depositProcedure": {
"min_deposit": [
{
"denom": "iris-atto",
"amount": "10000000000000000000"
}
],
"max_deposit_period": "20"
}
}
}
```
=> IRISHUB-327:generate the param.json file

app/genesis.go
http://jira.bianjie.ai/browse/IRISHUB-444
=> IRISHUB-444: The stake token in genesis initialize is wrong.

client/lcd/swaggerui/swagger.json
Tools to check and preview swagger-ui: [swaggerhub](https://app.swaggerhub.com)
Just create a new API project on swaggerhub and copy the swagger.json to the text box.
For instance: https://app.swaggerhub.com/apis/irisnet/irislcd/1.0
There is a demo irislcd page: http://111.231.70.168:1317/swagger-ui/
=> IRISHUB-360: implement swagger-ui

Dockerfile
http://jira.bianjie.ai/browse/IRISHUB-446
=> IRISHUB-446: add make get_tools

app/app.go
http://jira.bianjie.ai/browse/IRISHUB-485
I have verified this fix by creating new validators in my private network.
=> [R4R]: Fix consensus failure when creating validator

client/stake/cli/sendtx.go, client/stake/common.go
http://jira.bianjie.ai/browse/IRISHUB-477
=> [R4R]: fix IRISHUB-477

client/context/query.go, client/context/txcontext.go
http://jira.bianjie.ai/browse/IRISHUB-480
=> fix IRISHUB-480

Dockerfile, Dockerfile-dev
Update golang's version to 1.11
=> Fix docker build error

Gopkg.lock, client/clitest/iservice_test.go, client/clitest/utils.go
=> R4R: cli_test for iservice definition cmd

Makefile, client/clitest/irismon_test.go
=> R4R: cli_test for monitor cmd and update Makefile

client/clitest/iservice_test.go
When sync with develop, commit some mistake to develop.
=> R4R: fix a wrong commit

docs/zh/modules/record/README.md
=> R4R: Create user guide for record module

CHANGELOG.md, Gopkg.lock, Gopkg.toml, client/record/cli/sendtx.go, modules/record/errors.go, modules/record/msgs.go, version/version.go
Record improvement for issues #452 & #453 :
1. Limit description option input length
2. Offload input params check to ValidateBasic()
=> R4R: record improvement for #452 & #453 on dev branch

client/clitest/record_test.go, client/clitest/utils.go, client/record/cli/download.go, client/record/cli/query.go, modules/record/errors.go, modules/record/msgs.go
Add record cli test and fix issue #452 & #453
=> R4R: Add record cli test and fix issue #452 & #453

client/iservice/cli/flags.go, client/iservice/cli/query.go, docs/modules/iservice/README.md, docs/zh/modules/iservice/README.md, modules/iservice/error.go, modules/iservice/keeper_keys.go, modules/iservice/msgs.go
=> R4R: Bug fix for iservice

docs/cli-client/stake/README.md, docs/cli-client/stake/create-validator.md, docs/cli-client/stake/delegate.md, docs/cli-client/stake/delegation.md, docs/cli-client/stake/delegations.md, docs/cli-client/stake/edit-validator.md, docs/cli-client/stake/parameters.md, docs/cli-client/stake/pool.md, docs/cli-client/stake/redelegate.md, docs/cli-client/stake/redelegation.md, docs/cli-client/stake/redelegations-from.md, docs/cli-client/stake/redelegations.md, docs/cli-client/stake/signing-info.md, docs/cli-client/stake/unbond.md, docs/cli-client/stake/unbonding-delegation.md, docs/cli-client/stake/unbonding-delegations-from.md, docs/cli-client/stake/unbonding-delegations.md, docs/cli-client/stake/unjail.md, docs/cli-client/stake/validator.md, docs/cli-client/stake/validators.md, docs/cli-client/status/README.md, docs/zh/cli-client/status/README.md
This is related with issue #563
=> R4R: Add doc for status subcmd

docs/cli-client/keys/README.md
=> Update description begin with a capital letter

app/app.go, app/genesis.go, cmd/iris/main.go, init/init.go, init/init_test.go, init/testnet.go, init/utils.go
* Fix bug in collect gentx
* Remove useless function IrisAppInit
* Fix account export issue
* Fix init_test
=> R4R: Fix bugs in collect gentx and remove useless IrisAppInit

docs/.vuepress/override.styl
Optimize document website navbar #715
=> R4R: Optimize document website navbar

client/distribution/cli/query.go, client/distribution/lcd/query.go, client/gov/lcd/sendtx.go, client/service/lcd/sendtx.go, tools/protoidl/parse.go, tools/protoidl/parse_test.go
=> R4R: bug fix for v0.8

keepers/params/keeper.go, keepers/params/pair.go, keepers/params/subspace.go, keepers/params/table.go, keepers/params/test_common.go
https://github.com/irisnet/irishub/issues/756
=> R4R: Refactored params keeper

app/baseapp.go, app/v0/genesis.go, client/clitest/stake_test.go, store/rootmultistore.go, types/context.go, types/gas.go, types/gas_test.go, types/store.go
* Enforce block maximum gas limit in DeliverTx
cosmos/cosmos-sdk#2795
=> R4R: Merge PRs from Cosmos-SDK 0.27

modules/distribution/keeper/hooks.go, modules/distribution/keeper/validator.go, modules/distribution/keeper/validator_test.go
refer to: https://github.com/cosmos/cosmos-sdk/issues/2914
=> R4R: Removal of Mandatory Self-Delegation Reward

client/guardian/cli/flags.go, client/guardian/cli/query.go, client/guardian/cli/sendtx.go, cmd/iriscli/main.go, modules/guardian/error.go, modules/guardian/genesis.go, modules/guardian/handler.go, modules/guardian/keeper.go, modules/guardian/keeper_test.go, modules/guardian/msgs.go, modules/guardian/tags/tags.go, modules/guardian/types.go, modules/guardian/wire.go, server/init/testnet.go, tests/cli/guardian_test.go, tests/cli/utils.go
1. add delete handler
2. add profiler/trustee type, `genesis` type account can add/delete `ordinary` account
=> R4R: guardian refactor

Makefile, app/protocol/keeper/types.go, app/protocol/types.go, app/v0/protocol_v0.go, cmd/iris/main.go, cmd/iriscli/main.go, cmd/irislcd/main.go, cmd/iristool/main.go, modules/gov/execute.go, modules/upgrade/genesis.go, modules/upgrade/types.go, tests/cli/utils.go, tools/prometheus/server_test.go, types/address.go, types/prefix.go, types/protocol.go
Move prefix.go and protocol.go to /types
=> R4R: Move prefix.go and protocol.go to /types

app/v0/protocol_v0.go, lite/swagger-ui/swagger.yaml, modules/auth/genesis.go, modules/distribution/genesis.go, modules/mock/app.go, modules/stake/genesis.go
closes: https://github.com/irisnet/irishub/issues/909
=> R4R: Fix a bug in stake genesis initialization

modules/gov/genesis.go, modules/gov/test_common.go
closes: https://github.com/irisnet/irishub/issues/911
=> R4R: Fix issue that Gov initialization fail to reset Proposal-ID to 1

modules/distribution/keeper/allocation.go, tests/cli/guardian_test.go, tests/cli/stake_test.go, tests/cli/utils.go
Issue: https://github.com/irisnet/irishub/issues/916
=> R4R: If a validator is jailed, distribute no reward to it

client/guardian/cli/sendtx.go, modules/gov/execute.go
=> R4R: check destination address is a trustee when TaxUsage proposal execute

types/coin.go, types/coin_test.go
Fix the issue : https://github.com/cosmos/cosmos-sdk/pull/3207
=> R4R : Fix issue that miss checking the first one in Coins

app/protocol/patches.go
To be used by class3 upgrades (patches)
=> R4R: Define switch heights for protocol patches

app/app.go, app/baseapp.go, app/protocol/engine.go, app/v0/protocol_v0.go, cmd/iris/main.go, cmd/iriscli/main.go, cmd/irislcd/main.go, cmd/iristool/main.go, lite/test_helpers.go, modules/gov/simulation/sim_test.go, modules/gov/test_common.go, modules/upgrade/test_common.go, server/init/init_test.go, tests/cli/utils.go, tools/debug/hack.go, tools/debug/main.go, tools/prometheus/server_test.go, types/codec.go, types/protocol.go
* configure protocol keeper with its own codec
* make clients to always use the latest codec
=> R4R: Configure protocol keeper with its own codec

modules/gov/govparams_util.go
=> R4R: Fix the system_halt_period bug

modules/stake/simulation/invariants.go, modules/stake/types/validator.go
closes: https://github.com/irisnet/irishub/issues/963, https://github.com/irisnet/irishub/issues/981 and http://jira.bianjie.ai/browse/IRISHUB-1014
=> R4R: Fix issue cased by truncation in delegate share rate calculation

modules/stake/types/params.go
Closes: https://github.com/irisnet/irishub/issues/989
=> R4R: bug fix for type conversion

modules/slashing/params.go
=> R4R: Fix the  bug that slashing/MaxEvidenceAge can't be changed

modules/auth/params.go
=> R4R: Fix the wrong range of auth/gasPriceThreshold

modules/slashing/params.go
=> R4R: Fix the Unit dislocation in ERROR message of ParameterChange/slashing

modules/gov/errors.go, modules/gov/msgs.go
=> R4R: Fix the bug that empty param isn't be checked

modules/gov/errors.go, modules/gov/queryable.go
=> R4R: Fix the error msg

client/context/broadcast.go, modules/distribution/keeper/validator.go
=> R4R: Fix bug in changing validator delgation accumulation update height

cmd/iriscli/main.go
closes: https://github.com/irisnet/irishub/issues/1005
=> R4R: Print error if client receives a string-typed panic

app/v0/protocol_v0.go, client/gov/cli/query.go, client/gov/cli/sendtx.go, client/gov/lcd/sendtx.go, client/gov/utils.go, modules/gov/execute.go, modules/gov/handler.go, modules/gov/msgs.go, modules/params/helper.go, modules/params/keeper.go, modules/service/test_common.go
Closes:  https://github.com/irisnet/irishub/issues/1003
=> R4R: ParamSets within params keeper

modules/gov/errors.go, modules/gov/handler.go, modules/gov/keeper.go
=> R4R: Increase the cost of submitting proposals

app/v0/invariants.go, client/stake/cli/sendtx.go, modules/bank/invariants.go, modules/distribution/invariants.go, modules/distribution/keeper/validator.go, modules/distribution/types/keepers.go, modules/distribution/types/validator_info.go, modules/stake/invariants.go
=> R4R: Add more invariant checking for distribution and stake

app/v0/invariants.go, client/stake/cli/sendtx.go, modules/bank/simulation/invariants.go, modules/distribution/keeper/validator.go, modules/distribution/simulation/invariants.go, modules/distribution/types/keepers.go, modules/distribution/types/validator_info.go, modules/stake/simulation/invariants.go
This PR is the same as https://github.com/irisnet/irishub/pull/1034, just for different branch
=> R4R: Improve invariant coverage and fix distribution bugs

app/v0/export.go, server/export.go
=> R4R: Fix export genesis inconsistent issue

docs/software/export.md, docs/zh/software/export.md, server/export.go
close https://github.com/irisnet/irishub/issues/1060
refer to https://github.com/irisnet/irishub/issues/1040
=> R4R: Add flag --output-file to save result and ensure the result is consistent

docs/software/export.md, docs/zh/software/export.md, server/export.go
close https://github.com/irisnet/irishub/issues/1060
refer to https://github.com/irisnet/irishub/issues/1040
=> R4R:  Add flag --output-file to save result and ensure result is consistent

modules/gov/errors.go, modules/gov/execute.go, modules/gov/keeper.go, modules/gov/proposal_taxusage.go, modules/gov/proposal_upgrade.go, modules/gov/proposals.go, modules/gov/queryable.go
close https://github.com/irisnet/irishub/issues/1058
=> R4R: Query cmd should return details about software upgrade proposal

app/baseapp.go, app/protocol/types.go, app/v0/protocol_v0.go, modules/auth/params.go, modules/params/errors.go, modules/service/msgs.go, modules/service/params.go, types/errors.go
=> R4R: Service/TxSizeLimit

modules/mint/abci_app.go, modules/mint/minter.go, modules/mint/minter_test.go
closes: https://github.com/irisnet/irishub/issues/955
=> R4R: block mint doesn't depend on BFT time

modules/gov/errors.go, modules/gov/execute.go, modules/gov/keeper.go, modules/gov/proposal_taxusage.go, modules/gov/proposal_upgrade.go, modules/gov/proposals.go, modules/gov/queryable.go, modules/upgrade/handler.go, types/protocol.go
close https://github.com/irisnet/irishub/issues/1058
=>  Query cmd should return details about software upgrade proposal

modules/gov/msgs.go, modules/service/msgs.go
closes: https://github.com/irisnet/irishub/issues/1091 https://github.com/irisnet/irishub/issues/1092
=> R4R: Add SoftwareUpgradeProposal length check and fix bug

client/gov/cli/query.go
Target Issue: https://github.com/irisnet/irishub/issues/1095
=> R4R: Fix cli query proposals error

Makefile, scripts/setProdEnv.sh, types/address_test.go, types/config.go
Target Issue: https://github.com/irisnet/irishub/issues/1101
=> R4R: Improve bech32 prefixes config

modules/gov/execute.go, modules/gov/handler.go, modules/gov/keeper.go, modules/slashing/keeper.go, modules/slashing/params.go, modules/slashing/tick.go, modules/upgrade/handler.go, modules/upgrade/keeper.go, modules/upgrade/tally.go
Target Issue: https://github.com/irisnet/irishub/issues/1051
=> R4R: Slash,Gov and Upgrade Logger

app/v0/invariants.go, modules/distribution/abci_app.go, modules/distribution/handler.go, modules/distribution/keeper/allocation.go, modules/distribution/keeper/delegation.go, modules/distribution/keeper/validator.go, modules/distribution/types/delegator_info.go, modules/distribution/types/delegator_info_test.go, modules/distribution/types/fee_pool.go, modules/distribution/types/fee_pool_test.go, modules/distribution/types/total_accum.go, modules/distribution/types/total_accum_test.go, modules/distribution/types/validator_info.go, modules/distribution/types/validator_info_test.go, modules/mint/abci_app.go
Target Issue: https://github.com/irisnet/irishub/issues/1051
=> R4R: refactor mint and distribution log

app/baseapp.go, modules/gov/handler.go, modules/service/handler.go, modules/service/keeper.go, modules/slashing/keeper.go, modules/stake/handler.go, modules/stake/keeper/_store.md, modules/stake/keeper/delegation.go, modules/stake/keeper/slash.go, modules/stake/keeper/val_state_change.go, modules/stake/keeper/validator.go, modules/upgrade/handler.go
Target Issue: https://github.com/irisnet/irishub/issues/1051
=> R4R: Improve the log for stake/slashing/service

modules/distribution/keeper/delegation.go, modules/distribution/types/delegator_info.go, modules/gov/execute.go, modules/mint/abci_app.go, modules/slashing/keeper.go, modules/slashing/tick.go, modules/stake/keeper/slash.go
=> R4R: Check all logs with uniform standards

app/v0/protocol_v0.go, modules/distribution/keeper/allocation.go, modules/mint/keeper.go, modules/service/handler.go, modules/stake/keeper/delegation.go, modules/stake/keeper/val_state_change.go, modules/stake/keeper/validator.go, modules/upgrade/handler.go
Target Issue: https://github.com/irisnet/irishub/issues/1114
=> R4R: Go through all the panics

app/v0/protocol_v0.go, modules/distribution/keeper/allocation.go, modules/mint/keeper.go, modules/service/handler.go, modules/stake/keeper/delegation.go, modules/stake/keeper/val_state_change.go, modules/stake/keeper/validator.go, modules/upgrade/handler.go
Target Issue: https://github.com/irisnet/irishub/issues/1114 
Same as: https://github.com/irisnet/irishub/pull/1131
=> R4R: Go through all the panics for v0.11

client/tendermint/rpc/status.go
=> R4R: Make the output of iriscli status indent

client/gov/utils.go
=> R4R: Fix the iriscli gov error

client/gov/utils.go
=> R4R: Fix the iriscli gov error for release0.11

Gopkg.lock, client/stake/cli/sendtx.go, client/stake/lcd/sendtx.go, client/stake/utils.go, lite/swagger-ui/swagger.yaml
=> R4R: Add share percent in lcd unbond and redelegate

app/app.go, app/v0/protocol_v0.go, modules/distribution/alias.go, modules/distribution/keeper/allocation.go, modules/distribution/keeper/delegation.go, modules/distribution/keeper/keeper.go, modules/distribution/keeper/metrics.go, modules/gov/test_common.go
close https://github.com/irisnet/irishub/issues/1172
=> R4R: Add distribution metrics

app/v0/protocol_v0.go, modules/service/handler.go, modules/service/keeper.go, modules/service/metrics.go, modules/service/test_common.go, modules/stake/keeper/metrics.go
close: https://github.com/irisnet/irishub/issues/1173
=> R4R: Add service metrics

app/v0/protocol_v0.go, modules/upgrade/handler.go, modules/upgrade/keeper.go, modules/upgrade/metric.go, modules/upgrade/test_common.go
=> R4R: Finish the upgrade metric

app/v0/protocol_v0.go, modules/gov/execute.go, modules/gov/handler.go, modules/gov/keeper.go, modules/gov/metrics.go, modules/gov/test_common.go, tests/sim/gov/sim_test.go
Close #1171 
```
iris_module_gov_parameter{parameter_key="Inflation"} 3.4e-06
iris_module_gov_proposal_status{proposalID="1"} 3
iris_module_gov_vote{proposalID="1",validator_address="fca126zfy2jpv3vwgn59emp0vyr9cw2s8ahup2sufp"} 1
iris_module_gov_vote{proposalID="1",validator_address="fca18f7q42zn278dcv8xnn0chv2vf5ha08eu5a7y2e"} 1
```
=> R4R: Finish the gov metrics

app/app.go, app/baseapp.go, app/options.go, app/v0/invariants.go, app/v0/metrics.go, app/v0/protocol_v0.go, cmd/iris/main.go, server/config/config.go, server/config/toml.go, server/start.go
=> R4R:  Add invariant check metrics and move invariant level to iris.toml

modules/stake/keeper/delegation.go
=>  R4R: Fix the unbond error msg

docs/.vuepress/config.js
=> Fix config.js

client/flags.go
closes: https://github.com/irisnet/irishub/issues/1248
=> R4R: Fix gas simulate issue

Makefile, scripts/setTestEnv.sh
=> R4R: Configure the default build environment as mainnet

client/stake/cli/flags.go, client/stake/cli/sendtx.go, docs/cli-client/stake/create-validator.md, docs/features/stake.md, docs/get-started/Validator-Node.md, docs/zh/cli-client/stake/create-validator.md, docs/zh/features/stake.md, docs/zh/get-started/Validator-Node.md, modules/stake/handler.go, server/init/gentx.go, server/init/testnet.go, tests/cli/stake_test.go
=> R4R: Set max commission rate and max commission change rate to 100%

app/app.go, app/baseapp.go, app/options.go, app/v0/protocol_v0.go, cmd/iris/main.go, docker-compose.yml, modules/bank/handler.go, modules/bank/keeper.go, modules/distribution/keeper/allocation.go, modules/distribution/keeper/delegation.go, modules/distribution/keeper/hooks.go, modules/distribution/keeper/validator.go, modules/gov/handler.go, modules/gov/keeper.go, modules/service/handler.go, modules/service/keeper.go, modules/slashing/tick.go, modules/stake/handler.go, modules/stake/keeper/delegation.go, server/config/config.go, server/config/toml.go, tools/debug/hack.go, types/context.go, types/contexttags.go
Related issue: https://github.com/irisnet/irishub/issues/938
=> R4R: implement coin flow record

app/baseapp.go, app/helpers.go
closes: #1272 
Fix panic issue and fix simulated gas too low issue
=> R4R: Fix simulated gas too low issue

client/stake/utils.go
=> display correct validator consensus pubkey

Gopkg.lock, Gopkg.toml, Makefile, crypto/ledger.go, crypto/ledger_secp256k1.go
- **account signing by Ledger** 
- **validator signing by Ledger and yubihsm**
=> R4R: Make KMS available

docs/zh/get-started/Install-the-Software.md
tar command can't unzip zip,need unzip command
=> tar can't unzip zip,need unzip command

modules/bank/codec.go, modules/bank/handler.go, modules/bank/msgs.go, modules/bank/msgs_test.go, modules/stake/keeper/test_common.go, version/version.go
=> Revert "R4R: remove unused msg in the bank module"

client/stake/utils.go, modules/distribution/keeper/allocation.go, modules/distribution/keeper/metrics.go
fix in branch `master` and then merge to branch `develop`.
=> R4R: Fix bug for validator query and metrics

CHANGELOG.md, Gopkg.lock, Gopkg.toml, client/tendermint/tx/searchtx.go, docs/cli-client/tendermint/txs.md, docs/zh/cli-client/tendermint/txs.md, version/version.go
closes: https://github.com/irisnet/irishub/issues/1349
=> R4R: update txs search example && release version 0.13.0-rc0

client/distribution/utils.go
Closes: https://github.com/irisnet/irishub/issues/1363
=> R4R: Fix rewards compute

modules/stake/handler.go, modules/stake/tags/tags.go
Closes: https://github.com/irisnet/irishub/issues/1369
=> R4R: Add more tags for redelegate

modules/stake/handler.go, modules/stake/handler_test.go, modules/stake/keeper/delegation.go
Closes: https://github.com/irisnet/irishub/issues/1383
=> R4R: Improve result tags for unbond and redelegate

app/v0/protocol_v0.go, client/service/cli/query.go, client/service/lcd/query.go, cmd/iriscli/main.go, modules/service/error.go, modules/service/keeper.go, modules/service/querier.go
=> R4R: Refactor service query using Querier

app/v0/protocol_v0.go, client/gov/cli/query.go, client/gov/lcd/flags.go, client/gov/lcd/query.go, client/gov/lcd/rest.go, cmd/iriscli/main.go, lite/swagger-ui/swagger.yaml, modules/auth/querier.go, modules/distribution/keeper/querier.go, modules/gov/queryable.go, modules/guardian/querier.go, modules/params/querier.go, modules/service/querier.go, modules/stake/querier/queryable.go, types/queryable.go
Ref: https://github.com/irisnet/irishub/issues/1374
=> R4R: Add params querier and clean code

LICENSE
=> Merge LICENSE to develop

client/keys/cli/add.go, client/keys/cli/list.go, client/keys/cli/root.go, client/keys/cli/show.go, client/keys/utils.go
Resolves: https://github.com/irisnet/irishub/issues/1411
=> R4R: Add json-indent for keys operation

client/stake/cli/query.go, modules/stake/querier/queryable.go, modules/stake/stake.go
=> R4R: Fix redelegation query by using Querier

modules/distribution/types/params.go
Resolves: https://github.com/irisnet/irishub/issues/1409
=> R4R: Fix genesis communityTax validation bug

modules/gov/proposals.go, modules/slashing/params.go
=> R4R: Fix decimal output format

client/bank/cli/query.go, client/bank/lcd/query.go, client/bank/utils.go, docs/cli-client/bank/token-stats.md, docs/features/mint.md, docs/software/monitor.md, docs/zh/cli-client/bank/token-stats.md, docs/zh/features/mint.md, lite/swagger-ui/swagger.yaml
=> R4R: Replace loosen token with loose tokens

go.mod, go.sum
Update tendemrint version for test. @shilei-wang
=> R4R: Update Tendermint to v0.28.0

client/tendermint/tx/rest.go, docs/light-client/README.md, docs/zh/light-client/README.md, lite/swagger-ui/swagger.yaml
Resolves: https://github.com/irisnet/irishub/issues/1245
=> R4R: Drop txs post

modules/auth/querier.go
Resolves: #1375
Ref: https://github.com/irisnet/irishub/pull/1425
=> R4R: Fix token stats bug

client/bank/cli/sendTx.go
Resolves: https://github.com/irisnet/irishub/issues/1443
=> R4R: Skip account check in generate-only mode

modules/auth/querier_test.go
=> R4R: Fix unit test

lite/swagger-ui/swagger.yaml
Resolves: https://github.com/irisnet/irishub/issues/1456
=> R4R: Replace ICS with module name and revert post redelegation

app/v1/asset/errors.go, app/v1/asset/genesis.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/keeper_keys.go, app/v1/asset/keeper_test.go, app/v1/asset/msgs.go, app/v1/asset/params.go, app/v1/asset/querier.go, app/v1/asset/test_common.go, app/v1/asset/wire.go
Add empty asset module
resolves: #1468
=> R4R: Add asset module

app/v1/gov/codec.go, app/v1/gov/execute.go, app/v1/gov/govparams_util.go, app/v1/gov/keeper.go, app/v1/gov/msgs.go, app/v1/gov/proposal_text.go, app/v1/gov/proposals.go, client/gov/cli/sendtx.go, docs/features/governance.md, docs/zh/features/governance.md, lite/swagger-ui/swagger.yaml
=> R4R: Restore PlainTextProposal

docs/software/How-to-install-irishub.md, docs/zh/software/How-to-install-irishub.md
* Update Latest version to v0.14.0
* Remove dep in build
=> R4R: Update install doc

app/v1/gov/errors.go, app/v1/gov/execute.go, app/v1/gov/handler.go, app/v1/gov/msgs.go, client/gov/cli/sendtx.go, client/gov/lcd/sendtx.go, client/gov/utils.go, docs/cli-client/gov/submit-proposal.md, docs/zh/cli-client/gov/submit-proposal.md
=> R4R: Restrict ParameterChangeProposal to modify one parameter at a time

client/bank/lcd/query.go, lite/swagger-ui/swagger.yaml
Resolves: https://github.com/irisnet/irishub/issues/1486
=> R4R: Do not convert lcd account query result

app/v1/asset/keeper.go, app/v1/asset/test_common.go, app/v1/auth/ante.go, app/v1/auth/ante_test.go, app/v1/auth/stdtx.go, client/keys/cli/add.go, client/keys/cli/delete.go, client/tx/cli/multisign.go, client/tx/cli/sign.go, client/utils/utils.go, cmd/iriscli/main.go, crypto/keys/codec.go, crypto/keys/keybase.go, crypto/keys/types.go, modules/auth/ante_test.go, modules/auth/stdtx.go
Resolves: https://github.com/irisnet/irishub/issues/1466
=> R4R: Support multi signature account

client/bank/lcd/query.go, client/bank/lcd/sendtx.go, client/distribution/lcd/query.go, client/stake/lcd/utils.go
Resolves: https://github.com/irisnet/irishub/issues/1495
***All changes***
| API | case |  change |
| --- | ----- | ---------| 
| /bank/accounts/{address}  | invalid address |  http code 500 -> 400 |
| /bank/accounts/{address}/send | invalid recipient address | http code 500 -> 400 | 
| /distribution/{address}/rewards | invalid address | no error -> bad request | 
| /stake/delegators/{delegatorAddr}/validators/{validatorAddr}  | invalid delegatorAddr | no error -> bad request | 
| /stake/delegators/{delegatorAddr}/delegations/{validatorAddr} | invalid delegatorAddr | no error -> bad request |
=> R4R: Check lcd error handling

app/v1/asset/errors.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/msgs.go
=> R4R: Add gateway edition

app/v1/stake/handler_test.go, app/v1/stake/keeper/delegation.go
Resolves: https://github.com/irisnet/irishub/issues/1520
=> R4R: Enforce unbonding_time regardless of validator status

app/v1/stake/keeper/delegation_test.go
Resolves: https://github.com/irisnet/irishub/issues/1520
=> R4R: Fix v1 stake test

app/v1/gov/handler.go, app/v1/gov/tally.go, lite/swagger-ui/swagger.yaml
Resolves : #1526,#1527,#1528,#1529
=> R4R: Fix gov bugs

app/v1/asset/asset.go, app/v1/asset/family.go, app/v1/asset/source.go
=> R4R: Add base constructs for asset design

app/v1/asset/asset.go, app/v1/asset/params.go
=> R4R: Add gov params for the asset module

app/v1/params/errors.go
=> R4R: Add error codes for asset parameters

app/baseapp.go, app/protocol/engine.go, app/protocol/types.go, app/v0/protocol_v0.go, app/v1/asset/genesis.go, app/v1/asset/keeper.go, app/v1/distribution/keeper/keeper.go, app/v1/protocol_v1.go, server/init/testnet.go, server/init/utils.go
=> R4R: Add/modify constructs for correct init behavior

app/v1/asset/errors.go, app/v1/asset/gateway.go, app/v1/asset/genesis.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/keeper_keys.go, app/v1/asset/keeper_test.go, app/v1/asset/msgs.go, app/v1/asset/msgs_test.go, app/v1/asset/querier.go, client/asset/cli/flags.go, client/asset/cli/query.go, client/asset/cli/sendtx.go, cmd/iriscli/main.go
=> R4R: Modify gateway create

version/version.go
=> R4R: Add network type in version message

docs/software/How-to-install-irishub.md
=> R4R: Cherry pick doc fix to develop

app/v1/service/msgs.go
=> R4R: Check chain-id length in the service module

app/v1/distribution/invariants.go, app/v1/stake/invariants.go
Resolves: #1544
Related: #1548
=> R4R: Fix invariant check

.circleci/config.yml
=> R4R:  Add circleci config

crypto/keystore/keystore.go
Resolves: https://github.com/irisnet/irishub/issues/1551
=> R4R: Add empty KDF params check

client/keys/cli/add.go, client/keys/cli/delete.go, crypto/keys/keybase.go
Resolves: https://github.com/irisnet/irishub/issues/1557, https://github.com/irisnet/irishub/issues/1559, https://github.com/irisnet/irishub/issues/1560, https://github.com/irisnet/irishub/issues/1561
=> R4R: Improve the availability of multi-sign

app/v1/service/handler.go
=> R4R: Providers should be exempt from timeout slash under the profiling mode

app/v1/bank/keeper.go
Resolves: https://github.com/irisnet/irishub/issues/1578
=> R4R: Burn token if sending tokens to BurnedCoinsAccAddr

app/v1/asset/gateway.go, app/v1/asset/wire.go
=> R4R: Fix gateway msg cdc and add gateways check

app/v1/asset/keeper_keys.go, app/v1/asset/keeper_test.go, app/v1/asset/querier.go
1. change owner gateway key to fix iteration err
2. add keeper query tests for updated query logic check
Resolves: #1471
=> R4R: Change owner gateway key and add keeper query tests

app/v1/asset/asset.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/keeper_test.go, client/asset/cli/query.go, client/asset/cli/sendtx.go
- Add newly issued coins into owner's account
- Increase loosen tokens
Resolves: #1472
=> R4R: Add newly issued coins into owner's account

client/context/query.go
Resolves: https://github.com/irisnet/irishub/issues/1588
=> R4R: Convert asset to coin type

app/v1/asset/asset.go, app/v1/asset/errors.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/keeper_test.go, app/v1/asset/msgs.go, app/v1/asset/msgs_test.go, client/asset/cli/flags.go, client/asset/cli/sendtx.go
=> R4R: Handle asset issuing for gateways

app/v1/asset/asset.go, app/v1/asset/errors.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/msgs.go, app/v1/asset/msgs_test.go
=> WIP: Handle required fee for issuing an asset

app/v1/bank/keeper.go
Resolves: #1544
Related: #1548, #1563
=> R4R: Subtract BurnedCoinsAccAddr coins in v0 from looseToken

app/v1/asset/asset.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/keeper_test.go, app/v1/asset/msgs.go, app/v1/asset/querier.go, app/v1/asset/tags/tags.go, client/asset/cli/flags.go, client/asset/cli/query.go, client/asset/cli/sendtx.go, client/asset/lcd/query.go, client/asset/lcd/utils.go, client/context/query.go, client/tendermint/tx/searchtx.go, lite/swagger-ui/swagger.yaml
=> R4R: Add LCD API for Asset Query

app/baseapp.go, app/protocol/engine.go, app/v1/auth/keeper.go
* Load initial protocol with the upgrade info
* Loose token does not count tokens other than iris
Resolves: https://github.com/irisnet/irishub/issues/1578, https://github.com/irisnet/irishub/issues/1544, https://github.com/irisnet/irishub/issues/1472
Referance: https://github.com/irisnet/irishub/pull/1459
=> R4R: Make it easy to load and test any protocol version

client/bank/cli/query.go, client/bank/utils.go
=> R4R: Parse user issued coins

app/v1/bank/querier.go, app/v1/protocol_v1.go, client/bank/cli/query.go, client/bank/lcd/query.go, client/bank/lcd/rest.go, client/bank/utils.go, cmd/iriscli/main.go, docs/cli-client/bank/token-stats.md, docs/zh/cli-client/bank/token-stats.md, docs/zh/light-client/README.md, lite/swagger-ui/swagger.yaml, tests/cli/bank_test.go, tests/cli/utils.go
https://github.com/irisnet/irishub/issues/1579
=> R4R:  Add token-stats query by id

app/v1/asset/asset.go, app/v1/asset/keeper.go, app/v1/asset/keeper_test.go, app/v1/asset/msgs.go, app/v1/asset/msgs_test.go, app/v1/bank/querier_test.go, client/asset/cli/sendtx.go
=> R4R: Fix unit tests and bugs

app/v1/asset/family.go, app/v1/asset/fees.go, app/v1/asset/handler.go, app/v1/asset/msgs_test.go
=> R4R: Deduct fees for issuing tokens

app/v1/asset/params.go, client/bank/cli/query.go, tests/cli/asset_test.go, tests/cli/bank_test.go, tests/cli/utils.go
=> R4R: Fix cli test

.circleci/config.yml
=> R4R: Add unit tests support for CI

app/v1/asset/gateway.go
Modify gateways stringer to enable output for multiple owners
#1471
=> R4R: Modify gateways stringer

.circleci/config.yml, app/v1/asset/asset.go, app/v1/asset/keeper.go, app/v1/asset/keeper_test.go, app/v1/asset/msgs.go, app/v1/asset/msgs_test.go, types/coin_type.go, types/coin_type_test.go
Fixes: #1618 #1622 #1619 #1620 #1621 #1623 #1625
=> R4R: Fix bugs

client/asset/cli/sendtx.go
Modify cli handling logic to avoid signature verification failure when no all editable fields provided
#1497
=> R4R: Modify gateway edit cli

app/v1/bank/querier.go, docs/cli-client/asset/issue.md, docs/zh/cli-client/asset/issue.md
https://github.com/irisnet/irishub/issues/1626
=> R4R: Fix the bug

client/tendermint/tx/searchtx.go
Resolves: https://github.com/irisnet/irishub/issues/1643
=> R4R: Fix tx search by tx.height

client/tendermint/tx/searchtx.go
=> R4R: Hotfix tx search by tx.height

app/v1/asset/handler.go, app/v1/asset/tags/tags.go, tests/cli/asset_test.go, tests/cli/utils.go
=> R4R: Fix token issue fee for gateway

lite/swagger-ui/swagger.yaml
Resolves: https://github.com/irisnet/irishub/issues/1386
=> R4R: Add memo in BaseTx

tests/cli/asset_test.go
=> R4R: Fix asset cli test

client/asset/cli/flags.go, client/asset/cli/query.go, client/asset/cli/sendtx.go, client/asset/cli/utils.go
=> R4R: Add fee tips for gateway creation CLI

app/v1/auth/keeper.go
=> R4R: Fix inappropriate coin check in DecreaseTotalLoosenToken()

app/v1/asset/errors.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/keeper_test.go, app/v1/asset/msgs.go, app/v1/asset/msgs_test.go, app/v1/asset/wire.go, client/asset/cli/flags.go, client/asset/cli/sendtx.go, cmd/iriscli/main.go
=> R4R: Add gateway owner transfer

app/v1/asset/errors.go, app/v1/asset/fees.go, app/v1/asset/handler.go, app/v1/asset/msgs.go, app/v1/asset/msgs_test.go, client/asset/cli/flags.go, client/asset/cli/sendtx.go, client/asset/lcd/sendtx.go, tests/cli/asset_test.go
=> R4R: Remove the Fee field from gateway creation

lite/swagger-ui/swagger.yaml
=> R4R: Add fee query swagger

app/v1/asset/asset.go, app/v1/asset/handler.go, app/v1/asset/keeper.go, app/v1/asset/keeper_keys.go, app/v1/asset/keeper_test.go, app/v1/asset/querier.go, app/v1/auth/keeper.go, app/v1/auth/keeper_test.go, app/v1/bank/keeper.go, app/v1/bank/querier.go, app/v1/bank/querier_test.go, app/v1/gov/keeper.go, client/asset/lcd/utils.go, client/bank/cli/query.go, client/bank/lcd/query.go, client/bank/lcd/rest.go, client/bank/utils.go, go.sum, lite/swagger-ui/swagger.yaml, tests/cli/asset_test.go, tests/cli/bank_test.go, tests/cli/utils.go, types/asset.go, types/coin.go, types/coin_type.go
Resolves: #1603 
Blocks: #1673
=> R4R: Refactor Total Supply

app/v1/asset/asset.go, app/v1/asset/msgs.go, app/v1/asset/msgs_test.go, app/v1/asset/querier.go, go.mod, go.sum, tests/cli/bank_test.go
Resolves: #1641
Fixes: #1620 #1624
Todo: #1676
=> R4R: Support IRIS query in iriscli asset query-token

app/v1/asset/asset.go, app/v1/asset/msgs.go, app/v1/asset/querier.go, client/asset/cli/query.go, client/asset/cli/sendtx.go, client/asset/lcd/utils.go, cmd/iriscli/main.go, tests/cli/asset_test.go
Resolves: #1472
Todo: Fix cli test for this
=> R4R: Add token issue fee confirmation

app/v1/stake/keeper/delegation.go
Resolves: https://github.com/irisnet/irishub/issues/1383
=> R4R: Return current time if redelegate from an unbonded validator

app/v1/asset/gateway.go, app/v1/asset/genesis.go, app/v1/asset/genesis_test.go, app/v1/asset/keeper.go, app/v1/asset/keeper_test.go, app/v1/asset/msgs.go, app/v1/asset/querier.go
=> R4R: Add gateway genesis init and export

client/stake/lcd/query.go, client/stake/lcd/utils.go, client/tendermint/tx/querytx.go, client/tendermint/tx/searchtx.go, docs/cli-client/tendermint/tx.md, docs/cli-client/tendermint/txs.md, lite/swagger-ui/swagger.yaml
=> R4R: Add timestamp in tx query result for v0.14

client/asset/cli/flags.go, client/asset/cli/query.go, client/asset/lcd/utils.go, docs/cli-client/asset/query-fee.md, docs/zh/cli-client/asset/query-fee.md
=> R4R: Optimize fee query cli

go.mod, go.sum
tendermint -> v0.31.0
iavl -> v0.12.1
=> R4R: Update tendermint and iavl version

docs/cli-client/asset/create-gateway.md, docs/cli-client/asset/edit-gateway.md, docs/cli-client/asset/edit-token.md, docs/cli-client/asset/issue-token.md, docs/cli-client/asset/mint-token.md, docs/cli-client/asset/query-fee.md, docs/cli-client/asset/query-gateway.md, docs/cli-client/asset/query-gateways.md, docs/cli-client/asset/query-token.md, docs/cli-client/asset/query-tokens.md, docs/cli-client/asset/transfer-gateway-owner.md, docs/cli-client/asset/transfer-token-owner.md, docs/cli-client/bank/burn.md, docs/cli-client/bank/send.md, docs/features/asset.md, docs/zh/cli-client/asset/create-gateway.md, docs/zh/cli-client/asset/edit-gateway.md, docs/zh/cli-client/asset/edit-token.md, docs/zh/cli-client/asset/issue-token.md, docs/zh/cli-client/asset/mint-token.md, docs/zh/cli-client/asset/query-fee.md, docs/zh/cli-client/asset/query-gateway.md, docs/zh/cli-client/asset/query-gateways.md, docs/zh/cli-client/asset/query-token.md, docs/zh/cli-client/asset/query-tokens.md, docs/zh/cli-client/asset/transfer-gateway-owner.md, docs/zh/cli-client/asset/transfer-token-owner.md, docs/zh/cli-client/bank/burn.md, docs/zh/cli-client/bank/send.md, docs/zh/features/asset.md
=> R4R: Refactor asset docs

lite/swagger-ui/swagger.yaml
=> R4R: Update swagger

README.md
=> R4R: Update README

app/v1/asset/genesis_test.go, app/v1/asset/internal/keeper/ante_test.go, app/v1/asset/internal/keeper/keeper.go, app/v1/asset/internal/keeper/keeper_test.go, app/v1/asset/internal/types/expected_keepers.go, app/v1/asset/test_common.go, app/v1/distribution/types/params.go, app/v1/gov/test_common.go, app/v1/protocol_v1.go
=> R4R: Remove unless code & eliminate direct dependencies

app/v0/protocol_v0.go, app/v1/distribution/keeper/metrics.go, app/v1/gov/metrics.go, app/v1/protocol_v1.go, app/v1/service/metrics.go, app/v1/slashing/metrics.go, app/v1/stake/keeper/metrics.go, app/v1/upgrade/metrics.go, tools/prometheus/registry.go
=> R4R: Renew outdated prometheus metrics collectors

app/v0/protocol_v0.go, app/v1/distribution/keeper/metrics.go, app/v1/gov/metrics.go, app/v1/protocol_v1.go, app/v1/service/metrics.go, app/v1/slashing/metrics.go, app/v1/stake/keeper/metrics.go, app/v1/upgrade/metrics.go, tools/prometheus/registry.go
=> R4R: Cherry pick metrics fix to develop

app/v1/asset/exported/exported.go, app/v1/asset/internal/keeper/keeper.go, app/v1/asset/internal/types/msgs.go, app/v1/gov/errors.go, app/v1/gov/msgs.go, modules/gov/errors.go
Bug Fix :
1: the method "ValidateBasic" in the asset module does not take effect when Source=EXTERNAL
2: the error "unknown token id" occurred when issue EXTERNAL asset
Resolves : #1776 , #1774, #1777
=> R4R: Fix bug

crypto/keys/keybase.go
Resolves: https://github.com/irisnet/irishub/issues/1786
=> R4R: Only export local private keys

app/v1/coinswap/internal/keeper/keeper.go, app/v1/coinswap/internal/keeper/swap.go
It is confusing to use different function names in code and specifications
=> R4R: Refactor swap functions to match the design in the spec

docs/cli-client/keys/add.md, docs/cli-client/tx/multisig.md, docs/zh/cli-client/keys/add.md, docs/zh/cli-client/tx/multisig.md
=> update multisig doc

client/keys/cli/add.go, client/keys/input.go
=> R4R: Check tty for adding keys

app/v1/auth/feeauth.go, app/v1/bank/querier.go, client/keys/utils.go, modules/auth/querier.go, types/errors.go
Resolves: 
https://github.com/irisnet/irishub/issues/1783
https://github.com/irisnet/irishub/issues/1796
=> R4R: Optimize error messages

app/v1/asset/internal/types/asset.go
Resolves: https://github.com/irisnet/irishub/issues/1792
=> R4R: Return [] for empty assets

client/asset/cli/sendtx.go, docs/cli-client/asset/issue-token.md, docs/zh/cli-client/asset/issue-token.md
=> R4R: Mark decimal is required

app/v1/stake/types/params.go, client/distribution/utils.go, client/stake/utils.go, client/utils/utils.go, server/init/gentx.go
=> R4R: Simplify ExRateFromStakeTokenToMainUnit

app/v1/asset/internal/types/asset.go
Resolves: https://github.com/irisnet/irishub/issues/1710
=> R4R: Fix asset genesis check

CHANGELOG.md, docs/light-client/CHANGELOG.md
Resolves: https://github.com/irisnet/irishub/issues/1808
=> R4R: Release v0.15.0 Changelog

app/app.go, app/protocol/queryrouter.go, go.mod, go.sum, store/rootmultistore.go
Resolves: https://github.com/irisnet/irishub/issues/1808
=> R4R: Fix protocol version switch bug

modules/auth/ante.go, modules/auth/feeauth.go, modules/auth/keeper.go, modules/bank/keeper.go, modules/bank/msgs.go, modules/gov/msgs.go, modules/service/msgs.go, types/coin.go, types/coin_test.go
Resolves: https://github.com/irisnet/irishub/issues/1850
Revert breaking change: https://github.com/irisnet/irishub/pull/1843
=> R4R: Revert coin breaking change

app/v1/stake/keeper/delegation.go, app/v1/stake/keeper/delegation_test.go
Resolves: https://github.com/irisnet/irishub/issues/1854
=> R4R: Enforce unbonding_time for redelegation

app/baseapp.go, app/options.go, app/v1/auth/ante.go, app/v1/auth/ante_test.go, app/v1/auth/feeauth.go, app/v1/auth/genesis.go, app/v1/auth/keeper.go, app/v1/bank/keeper_test.go, app/v1/bank/msgs.go, app/v1/bank/msgs_test.go, app/v1/distribution/types/params.go, app/v1/gov/msgs.go, app/v1/service/keeper_test.go, app/v1/service/msgs.go, app/v1/stake/handler.go, app/v1/stake/keeper/delegation_test.go, app/v1/stake/types/msg.go, types/coin.go, types/coin_test.go, types/coin_type.go
=> Tighten validity checks for coins (protocol v1)

app/v2/coinswap/internal/keeper/keeper.go, app/v2/coinswap/internal/keeper/keeper_test.go, app/v2/coinswap/internal/keeper/querier.go, app/v2/coinswap/internal/keeper/swap.go, app/v2/coinswap/internal/keeper/swap_test.go, app/v2/coinswap/internal/types/errors.go
=> R4R: Refactor function and variable names for swap liquidity

app/v2/coinswap/handler.go, app/v2/coinswap/internal/keeper/keeper.go, app/v2/coinswap/internal/keeper/querier.go, app/v2/coinswap/internal/keeper/swap.go, app/v2/coinswap/internal/keeper/swap_test.go, app/v2/coinswap/internal/keeper/test_common.go, app/v2/coinswap/internal/types/errors.go, app/v2/coinswap/internal/types/params.go, app/v2/coinswap/internal/types/tags.go, client/context/context.go, types/coin.go
=> R4R: Add new function - Swap Coin

app/v1/bank/querier.go
=> R4R: Check validity of a token id when querying token stats

app/v2/coinswap/handler.go, app/v2/coinswap/internal/keeper/swap_test.go, app/v2/coinswap/internal/types/msgs.go, app/v2/coinswap/internal/types/test_common.go, client/coinswap/lcd/sendtx.go
=> R4R:  Change 'deadline' type from time.Time to int64

app/v1/bank/querier.go, types/coin.go, types/coin_test.go
=> R4R: Cherry pick token id validation

client/stake/utils.go
=> R4R: Fix precision in "stake pool" 

client/stake/utils.go
=> R4R: Fix precision in "stake pool"

app/v1/auth/account.go, app/v1/auth/feeauth.go, app/v1/bank/ante.go, app/v1/bank/codec.go, app/v1/bank/errors.go, app/v1/bank/handler.go, app/v1/bank/keeper.go, app/v1/bank/msgs.go, app/v1/protocol_v1.go, client/bank/cli/query.go, client/bank/cli/sendTx.go, client/bank/cli/sendtx.go, client/bank/lcd/rest.go, client/bank/lcd/sendtx.go, client/bank/utils.go, cmd/iriscli/main.go, docs/cli-client/bank/README.md, docs/cli-client/bank/account.md, docs/cli-client/bank/burn.md, docs/cli-client/bank/coin-type.md, docs/cli-client/bank/set-memo-regexp.md, docs/cli-client/bank/token-stats.md, types/errors.go
Resolves: https://github.com/irisnet/irishub/issues/1867
=> R4R: Add memo check by regexp

CHANGELOG.md, docs/light-client/CHANGELOG.md, lite/swagger-ui/swagger.yaml, version/version.go
=> R4R: Release v0.15.0-rc4

lite/swagger-ui/swagger.yaml, version/version.go
Related: https://github.com/irisnet/irishub/issues/1895
=> R4R: Update version to v0.15.1

app/v1/distribution/genesis.go, app/v1/export.go
Resolves: https://github.com/irisnet/irishub/issues/1897
=> R4R: Do not check if ValPool is zero

app/v1/distribution/keeper/keeper.go
Related: https://github.com/irisnet/irishub/pull/1898
=> R4R:  Fix feePool initialization from genesis

app/v2/coinswap/internal/keeper/swap.go, app/v2/coinswap/internal/keeper/swap_test.go
=> R4R: Fix coinswap bug[Formula parameter confusion error]

client/upgrade/cli/query.go
Resolves: https://github.com/irisnet/irishub/issues/1926
=> R4R: Fix upgrade query-signals example

docs/.vuepress/config.js, docs/features/asset.md, docs/get-started/Download-Rainbow.md, docs/get-started/Explorers.md, docs/get-started/Join-the-Mainnet.md, docs/get-started/Wallets.md, docs/software/How-to-install-irishub.md, docs/zh/get-started/Download-Rainbow.md, docs/zh/get-started/Explorers.md, docs/zh/get-started/Join-the-Mainnet.md, docs/zh/get-started/Validator-Node.md, docs/zh/get-started/Wallets.md, docs/zh/software/How-to-install-irishub.md
=> R4R: Cherrypick docs

app/v2/coinswap/internal/keeper/swap.go, app/v2/coinswap/internal/keeper/swap_test.go
=> R4R: Fix message error & add uint test case

app/v2/coinswap/internal/types/params.go, app/v2/protocol_v2.go
=> R4R: Delete the protocol v1  upgrade initialization code from protocol v2

app/app.go
Resolves: https://github.com/irisnet/irishub/issues/1944
=> R4R: fix protocol loading on replay-last-block

app/v1/auth/keeper.go, app/v2/htlc/abci.go, app/v2/htlc/alias.go, app/v2/htlc/exported/exported.go, app/v2/htlc/genesis.go, app/v2/htlc/genesis_test.go, app/v2/htlc/handler.go, app/v2/htlc/internal/keeper/keeper.go, app/v2/htlc/internal/keeper/keeper_keys.go, app/v2/htlc/internal/keeper/keeper_test.go, app/v2/htlc/internal/keeper/querier.go, app/v2/htlc/internal/types/cdc.go, app/v2/htlc/internal/types/errors.go, app/v2/htlc/internal/types/expected_keepers.go, app/v2/htlc/internal/types/genesis.go, app/v2/htlc/internal/types/htlc.go, app/v2/htlc/internal/types/msgs.go, app/v2/htlc/internal/types/msgs_test.go, app/v2/htlc/internal/types/params.go, app/v2/htlc/internal/types/querier.go, app/v2/htlc/internal/types/tags.go, app/v2/htlc/test_common.go
Resolves: https://github.com/irisnet/irishub/issues/1946
=> R4R: Add HTLC module and implement HTLC creation

app/v2/export.go
Resolves: #1897
Related: #1898
=> R4R: Do not check if ValPool is zero in v2

client/context/context.go, types/coin_type.go
=> R4R: Fix parseCoin error

app/v2/htlc/internal/keeper/keeper.go, app/v2/htlc/internal/keeper/keeper_keys.go, app/v2/htlc/internal/keeper/querier.go, app/v2/htlc/internal/types/htlc.go, app/v2/htlc/internal/types/msgs.go, app/v2/htlc/internal/types/params.go, client/htlc/cli/flags.go, client/htlc/cli/query.go, client/htlc/cli/sendtx.go, client/htlc/lcd/query.go, client/htlc/lcd/rest.go, client/htlc/lcd/senttx.go
=> R4R: Update HTLC docs

app/v2/htlc/internal/types/htlc.go, client/htlc/cli/flags.go, client/htlc/cli/query.go, client/htlc/cli/sendtx.go, client/htlc/lcd/query.go, client/htlc/lcd/senttx.go, cmd/iriscli/main.go
=> R4R: Improve HTLC

app/v2/htlc/internal/keeper/keeper.go, app/v2/htlc/internal/keeper/keeper_test.go
=> R4R: Fix HTLC claim

app/v1/gov/metrics.go, app/v1/stake/keeper/metrics.go, app/v1/upgrade/metrics.go, go.mod, tools/prometheus/registry.go
=> R4R: Fix prometheus bug

app/v1/gov/abci.go, modules/gov/handler.go
string(i int) will get the string by the `ASCII`.
=> R4R: Fix proposal-id tag

tests/cli/htlc_test.go
=> R4R: Fix CLI test for HTLC

.circleci/config.yml, docs/.vuepress/config.js
Disable docker_layer_caching to fix ci failed.
=> R4R: Fix ci failed

app/v2/coinswap/internal/keeper/keeper.go
=> R4R: Update calculation formula

docs/tools/monitor.md, docs/zh/tools/monitor.md
=> R4R: Update prometheus docs

CHANGELOG.md, go.mod, go.sum
=> R4R: Merge tenderminnt security patch to develop

.circleci/config.yml, CHANGELOG.md, docs/software/How-to-install-irishub.md, docs/zh/software/How-to-install-irishub.md, go.mod, go.sum, lite/swagger-ui/swagger.yaml, version/version.go
Ref: https://github.com/irisnet/tendermint/pull/101
=> R4R: Bump tendermint version

client/bank/cli/sendtx.go, client/distribution/cli/sendtx.go, client/gov/cli/sendtx.go, client/guardian/cli/sendtx.go, client/service/cli/sendtx.go, client/slashing/cli/sendtx.go, client/stake/cli/sendtx.go, docs/cli-client/asset.md, docs/zh/cli-client/asset.md, tests/cli/distribution_test.go, tests/cli/service_test.go
Resolves: https://github.com/irisnet/irishub/pull/2051#discussion_r341060034
=> R4R: Uniform fee and flag format

app/v2/htlc/alias.go, client/htlc/cli/sendtx.go
=> R4R: Add secret check in CLI

go.mod, go.sum, version/version.go
=> R4R: Resolve merge conflicts

server/snapshot.go
=> R4R: Fix bug(write wrong state height)

CHANGELOG.md, docs/get-started/install.md, docs/zh/get-started/install.md, lite/swagger-ui/swagger.yaml, version/version.go
=> R4R: Release 0.16.1

app/v3/asset/exported/exported.go, app/v3/asset/internal/keeper/keeper.go, app/v3/coinswap/alias.go, app/v3/coinswap/genesis.go, app/v3/coinswap/internal/keeper/keeper.go, app/v3/coinswap/internal/keeper/keeper_test.go, app/v3/coinswap/internal/keeper/pool.go, app/v3/coinswap/internal/keeper/querier.go, app/v3/coinswap/internal/keeper/querier_test.go, app/v3/coinswap/internal/keeper/swap.go, app/v3/coinswap/internal/keeper/swap_test.go, app/v3/coinswap/internal/keeper/test_common.go, app/v3/coinswap/internal/keeper/upgrade.go, app/v3/coinswap/internal/types/expected_keepers.go, app/v3/coinswap/internal/types/pool.go, app/v3/coinswap/internal/types/utils.go, app/v3/protocol_v3.go, client/asset/cli/sendtx.go
=> R4R: Change the liquidity pool from account to KV store

client/service/cli/flags.go, client/service/cli/query.go, tests/cli/service_test.go
=> R4R: Fix  service cli test

app/v3/asset/internal/types/querier.go
=> R4R: "asset token tokens" should returns "[]" if result is empty 

client/asset/cli/sendtx.go
=> R4R: fix "Token id" confused

app/v3/gov/msgs.go, client/gov/cli/sendtx.go
=> R4R: Fix amount check

app/v3/service/exported/exported.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/keeper/keeper.go, app/v3/service/internal/keeper/keeper_keys.go, app/v3/service/internal/types/errors.go, app/v3/service/internal/types/invocation.go
=> R4R: Implement interfaces for other modules

app/v3/service/alias.go, app/v3/service/handler.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/keeper/keeper_test.go, app/v3/service/internal/keeper/querier.go, app/v3/service/internal/types/errors.go, app/v3/service/internal/types/querier.go, app/v3/service/internal/types/tags.go, client/service/cli/query.go, client/service/lcd/query.go, cmd/iriscli/main.go
=> R4R: Enable service request query by ID and add tags

lite/swagger-ui/swagger.yaml
=> R4R: Add service swagger docs

app/v3/service/abci.go, app/v3/service/internal/keeper/keeper_keys.go, client/service/cli/query.go
=> R4R: Fix service invocation

client/service/cli/sendtx.go, client/service/lcd/sendtx.go
=> R4R: Fix ParseCoins call in client

app/v3/service/abci.go, app/v3/service/alias.go, app/v3/service/handler.go, app/v3/service/internal/keeper/binding.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/keeper/keeper_keys.go, app/v3/service/internal/keeper/keeper_test.go, app/v3/service/internal/keeper/querier.go, app/v3/service/internal/types/binding.go, app/v3/service/internal/types/errors.go, app/v3/service/internal/types/msgs.go, app/v3/service/internal/types/msgs_test.go, app/v3/service/internal/types/querier.go, client/service/cli/flags.go, client/service/cli/query.go, client/service/cli/sendtx.go, client/service/lcd/query.go, client/service/lcd/sendtx.go
=> R4R: Modify withdrawal address logic in service

client/service/cli/query.go, tests/cli/service_test.go, tests/cli/utils.go
=> R4R: Refactor service invocation CLI tests

lite/swagger-ui/swagger.yaml
=> R4R: Update service swagger

cmd/iriscli/main.go, tests/cli/service_test.go
=> R4R: Fix service CLI test

app/v3/protocol_v3.go, app/v3/service/abci.go, app/v3/service/handler.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/keeper/keeper_keys.go, app/v3/service/internal/keeper/querier.go, client/service/cli/sendtx.go, client/service/lcd/flags.go, client/service/lcd/query.go, lite/swagger-ui/swagger.yaml
=> R4R: Optimize service

app/v3/service/abci.go
=> R4R: Fix batch response count

app/v3/asset/internal/keeper/keeper_keys.go, app/v3/oracle/internal/keeper/feed.go, app/v3/oracle/internal/keeper/keeper.go, app/v3/oracle/internal/keeper/test_common.go, app/v3/oracle/internal/types/expected_keepers.go, app/v3/oracle/internal/types/feed.go, app/v3/rand/genesis_test.go, app/v3/service/abci.go, app/v3/service/alias.go, app/v3/service/genesis.go, app/v3/service/handler.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/keeper/keeper_test.go, app/v3/service/internal/keeper/querier.go, app/v3/service/internal/types/errors.go, app/v3/service/internal/types/invocation.go, app/v3/service/internal/types/msgs_test.go, tests/cli/service_test.go
=> R4R: Format ID using hex encoding

app/v3/oracle/internal/keeper/keeper.go, app/v3/oracle/internal/keeper/test_common.go, app/v3/service/abci.go, app/v3/service/handler.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/keeper/keeper_test.go, app/v3/service/internal/types/invocation.go
=> R4R: Add callback when response count is insufficient

app/v3/service/internal/types/binding.go
=> R4R: Modify output for the disabled time

app/options.go, app/v0/genesis.go, app/v1/asset/internal/keeper/querier.go, app/v1/asset/internal/types/asset.go, app/v1/asset/test_common.go, app/v1/auth/keeper.go, app/v1/bank/querier.go, app/v1/genesis.go, app/v1/gov/params.go, app/v1/gov/test_common.go, app/v1/rand/test_common.go, app/v1/service/keeper_test.go, app/v1/service/test_common.go, app/v2/coinswap/internal/types/utils.go, app/v2/genesis.go, app/v3/asset/internal/types/asset.go, app/v3/coinswap/internal/types/utils.go, app/v3/genesis.go, app/v3/gov/params.go, app/v3/service/internal/keeper/keeper_test.go, app/v3/service/internal/types/msgs_test.go, client/context/context.go, modules/gov/params.go, modules/gov/test_common.go, modules/service/test_common.go, types/coin.go, types/coin_test.go, types/coin_type.go, types/config.go
=> R4R: Improve FungibleToken related naming

app/v3/service/handler.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/types/errors.go
=> R4R: Add authority check for operations on the request context

app/v3/service/abci.go, app/v3/service/internal/keeper/invocation.go
=> R4R: Fix service

app/v3/rand/genesis_test.go, app/v3/rand/internal/keeper/keeper_test.go, app/v3/rand/internal/keeper/service_test.go, app/v3/service/abci.go, app/v3/service/handler.go, app/v3/service/internal/keeper/binding.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/keeper/keeper_test.go, app/v3/service/internal/types/binding.go, app/v3/service/internal/types/errors.go, app/v3/service/internal/types/msgs.go, app/v3/service/internal/types/msgs_test.go, client/service/cli/flags.go, client/service/cli/sendtx.go, client/service/lcd/sendtx.go, docs/cli-client/service.md, docs/zh/cli-client/service.md, lite/swagger-ui/swagger.yaml, tests/cli/oracle_test.go, tests/cli/rand_test.go, tests/cli/service_test.go
=> R4R: Modify service timeout logic

app/v3/asset/internal/keeper/querier.go, lite/swagger-ui/swagger.yaml
=> R4R: Fix asset

app/v3/oracle/internal/keeper/querier.go, app/v3/oracle/internal/keeper/querier_test.go, app/v3/oracle/internal/types/feed.go, lite/swagger-ui/swagger.yaml
=> R4R: Remove useless field

app/v3/asset/internal/keeper/querier.go, app/v3/asset/internal/types/querier.go, client/asset/cli/flags.go, client/asset/cli/query.go, client/asset/cli/sendtx.go, client/asset/cli/utils.go, client/asset/lcd/query.go, client/asset/lcd/rest.go, client/asset/lcd/sendtx.go, docs/cli-client/asset.md, docs/light-client/intro.md, docs/zh/cli-client/asset.md, docs/zh/light-client/intro.md, lite/swagger-ui/swagger.yaml, tests/cli/asset_test.go, tests/cli/utils.go
=> R4R: Improve asset

app/v3/asset/genesis_test.go, app/v3/asset/internal/keeper/fees.go, app/v3/asset/internal/types/errors.go
=> R4R: Remove gateway and tokenID related errors and comments

app/v3/rand/internal/keeper/keeper.go, client/coinswap/lcd/query.go
=> R4R: Fix coinswap api

app/v3/rand/internal/keeper/keeper.go, app/v3/service/abci.go, app/v3/service/alias.go, app/v3/service/internal/keeper/fees.go, app/v3/service/internal/keeper/invocation.go, app/v3/service/internal/keeper/keeper.go, app/v3/service/internal/keeper/keeper_keys.go, app/v3/service/internal/keeper/querier.go, app/v3/service/internal/keeper/upgrade.go, app/v3/service/internal/types/querier.go, client/service/cli/flags.go, client/service/cli/query.go, client/service/cli/sendtx.go, client/service/lcd/query.go, client/service/lcd/sendtx.go, client/service/utils/query.go, docs/cli-client/service.md, docs/zh/cli-client/service.md, lite/swagger-ui/swagger.yaml
=> R4R: Improve service

app/v3/oracle/internal/types/msgs.go, app/v3/rand/internal/types/msgs.go, app/v3/service/internal/types/msgs.go, client/rand/cli/sendtx.go
=> R4R: Fix empty slice signature verification failed

docs/package-lock.json, docs/package.json
cherry-pick from https://github.com/irisnet/irishub/pull/2346
=> R4R: Update docs dependencies

docs/features/service.md, docs/zh/features/service.md
=> R4R: Modify and complete service feature zh doc

app/app.go, go.mod, go.sum
=> add record module

docs/get-started/install.md, docs/zh/get-started/install.md
The latest version may be the rc version
=> Link to a specified version

modules/oracle/client/cli/tx.go
Closes: https://github.com/irisnet/irishub/issues/2427
=> Use file as input

cmd/iris/cmd/genaccounts.go, docs/daemon/local-testnet.md, docs/zh/daemon/local-testnet.md, go.mod, go.sum, modules/mint/module.go, simapp/test_helpers.go
* fix beginblock process
* add genesis account via keyring
* fix local testnet docs
=> fix bug and clean up

Dockerfile
=> update golang version

app/app.go, cmd/iris/cmd/root.go, go.mod, go.sum, simapp/app.go
Closes: https://github.com/irisnet/irishub/issues/2462
=> Add wasm module

Dockerfile, Makefile, docker-compose.yml
Fix docker build to add wasmvm libs
=> Fix docker build

app/encoding.go
=> Register legacy evidence

migrate/migrate.go, migrate/v0_16/service/genesis.go
* set service MinDeposit
* remove ServiceTaxCoinsAccAddr account
=> Fix migrate process

CHANGELOG.md, go.mod, go.sum, scripts/protoc-swagger-gen.sh
=> Release v1.0.0-rc1

go.mod, go.sum
=> Bump cosmos-sdk to v0.41.0

CHANGELOG.md, migrate/migrate.go
Migrate withdraw address infos
=> Migrate withdraw infos

app/app.go, go.mod, go.sum, simapp/app.go
1. Upgrade irismod to latest version
2. Add Service fee tax account
=> Upgrade irismod to latest version

CHANGELOG.md, go.mod, go.sum, scripts/protoc-swagger-gen.sh
Fixed: https://github.com/irisnet/irishub/issues/2570
=> Bump cosmos-sdk version to v0.41.3

docs/get-started/testnet.md, docs/zh/get-started/testnet.md
* update testnet instructions
* update testnet instructions
=> Update testnet instructions (#2578)

.github/workflows/BuildAndPublish.yml
get tag during buiding and append this tag to docker image as "irisnet/irishub:tag".
=> Update CI in Action

docs/features/service.md, docs/zh/features/service.md
=> Fix command typo

app/app.go, simapp/app.go
Refer: https://github.com/cosmos/cosmos-sdk/pull/9835
=> Fix cosmos-sdk v0.42.9 upgrade

docs/cli-client/farm.md, docs/zh/cli-client/farm.md
refer https://github.com/irisnet/irishub/issues/2625
=> Add farm module command docs

docs/get-started/explorers.md
We've just added support for Iris to ATOMScan and would love to be listed on your docs!
=> Adds ATOMScan to the blockchain explorers list

docs/get-started/mainnet.md
=> add faucet en

docs/get-started/testnet.md
=> remove redundant explorer

docs/zh/get-started/mainnet.md
=> add faucet cn

go.mod, go.sum, network/nft-transfer.md
=> update dependency packages

go.mod, go.sum
irismod Adjust the position of the query method in proto to solve the api coverage problem
=> chores(dep): bump up irismod
